### ISSUE TITLE
file indesiderati

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/maggiore#1]
hai caricato a.out e un file di backup

**Comment by FabioZTessitore** [comment]
questa te la perdono visto che altre volte lo hai già fatto, però cerca di fare attenzione a quello che carichi

**Comment by Teodoro777** [comment]
Ma avevo messo il .gitignore apposta

2016-02-27 9:48 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
